server:
  port: ${PORT:8100}

spring:
  datasource:
    url: jdbc:h2:mem:test_db
    driverClassName: org.h2.Driver
    username: sa
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost:29092}