server:
  port: 8000

spring:
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  kafka:
    producer:
      bootstrap-servers: localhost:29092